version: "3.7"
services:
    odoo16:
        image: odoo:17
        platform: linux/amd64
        container_name: odoo17
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "8069:8069"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgresql
        restart: always
    postgresql:
        image: postgres:16.2
        container_name: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo