version: "3.7"
services:
    odoo16:
        image: odoo:17
        #image: my_odoo_debug:17
        platform: linux/amd64
        container_name: odoo17
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "8069:8069"
            - "5678:5678"  # puerto para la depuracion remota
        volumes:
            - ./addons:/mnt/addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgresql
            #- PYTHONPATH=/mnt/extra-addons
            #- PYTHONBREAKPOINT=debugpy.breakpoint
            #- DEBUGPY_LOG_DIR=/var/log/debugpy
      
        restart: always
    postgresql:
        image: postgres:16.2
        container_name: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo